Repository Team-Umea/TravelPlanner, pull requests merged in 2025-02, with the labels that each got.

#1 add layout to develop
  db.json
  package-lock.json
  package.json
  src/assets/travel-planner-logo.svg
  src/components/dumb-components/ProtectedRoute.jsx
  src/components/header/Navbar.jsx
  src/components/header/NavbarBtn.jsx
  src/components/smart-components/AuthForm.jsx
  src/components/smart-components/FormInput.jsx
  src/constants/constants.js
  src/hooks/useAuthDB.js
  src/hooks/useAuthStore.js
  src/index.css
  src/layouts/Footer.jsx
  src/layouts/Header.jsx
  src/layouts/Navbar.jsx
  src/layouts/RootLayout.jsx
  src/main.jsx
  src/pages/AboutPage.jsx
  src/pages/FAQPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/TripsPage.jsx
  src/router/Router.jsx
  src/store/authSlice.js
  src/store/store.js
Labels: enhancement

#3 Feature#add trip
  .gitignore
  db.json
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/vite.svg
  src/App.jsx
  src/components/btn/DangerBtn.jsx
  src/components/btn/PrimaryBtn.jsx
  src/components/btn/SecondaryBtn.jsx
  src/components/trip/Input.jsx
  src/components/trip/TripForm.jsx
  src/constants/constants.js
  src/hooks/useApi.js
  src/index.css
  src/layouts/Footer.jsx
  src/layouts/Header.jsx
  src/layouts/Navbar.jsx
  src/layouts/RootLayout.jsx
  src/layouts/animation/PageTransition.jsx
  src/main.jsx
  src/pages/HomePage.jsx
  src/router/Router.jsx
  src/store/store.js
  src/utils/utils.js
  tailwind.config.js
  vite.config.js
Labels: help wanted

#4 Feature#add trip
  src/components/trip/Input.jsx
  src/components/trip/TripForm.jsx
  src/pages/HomePage.jsx
Labels: bug, enhancement, help wanted
